# Generated by Django 5.1.1 on 2024-09-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='user',
            new_name='name',
        ),
    ]
