# Generated by Django 5.1.1 on 2024-09-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_user_user_info_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='name',
            new_name='user',
        ),
    ]
